# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: cimg/go:1.13

    steps:
      - checkout

      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

      - run: make # pull and build dependencies for the project

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/home/circleci/go/pkg/mod"

      - store_artifacts: # upload test summary for display in Artifacts
          path: ./build

      - setup_remote_docker

      - run: |
          TAG=build-$CIRCLE_BUILD_NUM

          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

          docker build -f client.Dockerfile -t $DOCKER_USER/deploy-agent-client:$TAG .
          docker tag $DOCKER_USER/deploy-agent-client:$TAG $DOCKER_USER/deploy-agent-client:latest
          docker push $DOCKER_USER/deploy-agent-client:$TAG
          docker push $DOCKER_USER/deploy-agent-client:latest

          docker build -f server.Dockerfile -t $DOCKER_USER/deploy-agent-server:$TAG .
          docker tag $DOCKER_USER/deploy-agent-server:$TAG $DOCKER_USER/deploy-agent-server:latest
          docker push $DOCKER_USER/deploy-agent-server:$TAG
          docker push $DOCKER_USER/deploy-agent-server:latest

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
